"use client";

import { useEffect, useState } from "react";
import { DollarSign, Gift, TrendingUp, Wallet } from "lucide-react";
import { supabase } from "@/lib/supabase";

export default function DashboardPage() {
  const [user, setUser] = useState<any>(null); const [wallet, setWallet] = useState<any>(null); const [transactions, setTransactions] = useState<any[]>([]); const [message, setMessage] = useState("");
  useEffect(() => { (async () => { if (!supabase) return; const { data: auth } = await supabase.auth.getUser(); if (!auth.user) { setMessage("Please log in to view your dashboard."); return; } const [p,w,t] = await Promise.all([supabase.from("profiles").select("*").eq("id",auth.user.id).single(), supabase.from("wallets").select("*").eq("user_id",auth.user.id).single(), supabase.from("transactions").select("*").eq("user_id",auth.user.id).order("created_at",{ascending:false}).limit(10)]); setUser(p.data); setWallet(w.data); setTransactions(t.data || []); })(); }, []);
  const stats = [{label:"Wallet balance",value:`₦${Number(wallet?.wallet_balance||0).toLocaleString()}`,icon:Wallet},{label:"Available balance",value:`₦${Number(wallet?.available_balance||0).toLocaleString()}`,icon:DollarSign},{label:"Task earnings",value:`₦${Number(wallet?.task_earnings||0).toLocaleString()}`,icon:TrendingUp},{label:"Welcome bonus",value:`₦${Number(wallet?.welcome_bonus||0).toLocaleString()}`,icon:Gift}];
  return <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="mb-8"><p className="text-sm uppercase tracking-[0.2em] text-brand-300">User dashboard</p><h1 className="mt-2 text-3xl font-bold text-white">Good evening, {user?.full_name?.split(" ")[0] || "Member"}</h1></div>{message&&<p className="mb-5 text-rose-300">{message}</p>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{stats.map(({label,value,icon:Icon})=><div key={label} className="rounded-2xl border border-slate-800 bg-slate-900/80 p-5"><div className="flex justify-between text-sm text-slate-400">{label}<Icon className="h-4 w-4 text-brand-300"/></div><p className="mt-4 text-2xl font-bold text-white">{value}</p></div>)}</div><div className="mt-10 rounded-3xl border border-slate-800 bg-slate-900/80 p-6"><h2 className="text-xl font-semibold text-white">Recent transactions</h2><div className="mt-5 space-y-3">{transactions.length ? transactions.map((item)=><div key={item.id} className="flex justify-between rounded-2xl border border-slate-800 bg-slate-950/80 p-4"><div><p className="font-medium text-white">{item.description || item.type}</p><p className="text-sm text-slate-400">{new Date(item.created_at).toLocaleString()}</p></div><p className="font-semibold text-emerald-300">₦{Number(item.amount).toLocaleString()}</p></div>) : <p className="text-slate-400">No transactions yet.</p>}</div></div></div>;
}
